[package]
name = "hash"
version = "0.1.0"
edition = "2018"
authors = ["Elie Hess"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.9.6"
hex = "0.4.3"
sha3 = "0.10.0"
